services:
  - type: web
    name: veln-game-server
    env: python
    runtime: python-3.11
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: veln-super-secret-key-2024-render
      - key: BOT_TOKEN
        value: 7372299924:AAEkfBmorTJ7QKFRz1snSCEklVwbllr-rXg
databases:
  - name: veln-game-db
    databaseName: veln_game
    user: veln_user